{
 "title": "Bybit Spot vs Perpetual",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "250ms",
 "panels": [
  {
   "title": "BTC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"BTC_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 400\r\n",
     "selectedFormat": 2
    },
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"BTC_USDT_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 500",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "ETH",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"ETH_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 300",
     "selectedFormat": 2
    },
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"ETH_USDT_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 400",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "XRP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"XRP_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 300",
     "selectedFormat": 2
    },
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"XRP_USDT_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 400",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "BNB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"BNB_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 100",
     "selectedFormat": 2
    },
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"BNB_USDT_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 200",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "SOL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"SOL_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 300\r\n",
     "selectedFormat": 2
    },
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"SOL_USDT_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 400",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "DOGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"DOGE_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 300",
     "selectedFormat": 2
    },
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"DOGE_USDT_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 400",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "ADA ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"ADA_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 300"
    },
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"ADA_USDT_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 300",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "TRX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"TRX_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 300",
     "selectedFormat": 2
    },
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"TRX_USDT_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 400",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "SUI",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"SUI_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 300",
     "selectedFormat": 2
    },
    {
     "rawSql": "SELECT timestamp as time, timestamp, close FROM \"SUI_USDT_USDT\" WHERE $__timeFilter(timestamp) SAMPLE BY $__sampleByInterval ALIGN TO CALENDAR ORDER BY timestamp DESC LIMIT 400",
     "selectedFormat": 2
    }
   ]
  }
 ]
}